In [1]:
import pandas as pd
import numpy as np
import re
import string
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [3]:
stop_words = set(stopwords.words('english'))

In [4]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [5]:
df = pd.read_excel("train.xlsx")

In [6]:
df

                                                 Reviews Sentiment
0      When I first tuned in on this morning news, I ...       neg
1      Mere thoughts of "Going Overboard" (aka "Babes...       neg
2      Why does this movie fall WELL below standards?...       neg
3      Wow and I thought that any Steven Segal movie ...       neg
4      The story is seen before, but that does'n matt...       neg
...                                                  ...       ...
24995  Everyone plays their part pretty well in this ...       pos
24996  It happened with Assault on Prescient 13 in 20...       neg
24997  My God. This movie was awful. I can't complain...       neg
24998  When I first popped in Happy Birthday to Me, I...       neg
24999  So why does this show suck? Unfortunately, tha...       neg

[25000 rows x 2 columns]

In [7]:
df.columns.unique()

Index(['Reviews', 'Sentiment'], dtype='object')

In [8]:
def preprocess_text(text):
    """Cleans and tokenizes text data."""
    if not isinstance(text, str):  # Convert non-string values to string
        text = str(text)
    text = text.lower()
    text = re.sub(f"[{string.punctuation}]", "", text)  # Remove punctuation
    text = re.sub("\d+", "", text)  # Remove numbers
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

In [9]:
# Apply preprocessing
df['Reviews'] = df['Reviews'].apply(preprocess_text)

In [10]:
df['Reviews']

0        first tuned morning news thought wow finally e...
1        mere thoughts going overboard aka babes ahoy m...
2        movie fall well standards ultimately answer li...
3        wow thought steven segal movie bad every time ...
4        story seen matter figure make proper storyboar...
                               ...
24995    everyone plays part pretty well little nice mo...
24996    happened assault prescient happened lost boys ...
24997    god movie awful cant complain much went see gr...
24998    first popped happy birthday checked timer see ...
24999    show suck unfortunately really question doubt ...
Name: Reviews, Length: 25000, dtype: object

In [11]:
# Feature extraction using TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)
X = vectorizer.fit_transform(df['Reviews'])
y = df['Sentiment'].map({'pos': 1, 'neg': 0})

In [12]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Model training (Logistic Regression)
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [14]:
# Predictions
y_pred = model.predict(X_test)

In [15]:
# Evaluation
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

# Display results
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Accuracy: 0.88
Precision: 0.86
Recall: 0.89

In [16]:
import pickle

# Assuming `vectorizer` and `model` are already trained
with open("model.pkl", "wb") as file:
    pickle.dump((vectorizer, model), file)